mysite/mysite/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

from django.conf import settings
from django.views.generic import RedirectView

urlpatterns = [
    path('', RedirectView.as_view(url='/polls/', permanent=False)),
    path('polls/', include('polls.urls')),
    path('admin/', admin.site.urls),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mysite/polls/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from . import views

app_name = 'polls'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),

    path('register/', views.Registration.as_view(), name='register'),
    path('login/', auth_views.LoginView.as_view(template_name='polls/login.html'), name='login'),
    path('logout/', views.logout_view, name='logout'),

    path('profile/', views.Profile.as_view(), name='profile'),
    path('profile/edit/', views.ProfileUpdateView.as_view(), name='profile_update'),
    path('profile/delete/', views.ProfileDeleteView.as_view(), name='profile_delete')
]

mysite/polls/models.py
import datetime
from random import choice

from django.db import models
from django.utils import timezone
from django.contrib.auth.models import AbstractUser

class User(AbstractUser):
    username = models.CharField(max_length=150, verbose_name='Username', unique=True)
    avatar = models.FileField(upload_to='avatars/', verbose_name='Загрузите свой аватар')
    first_name = models.CharField(max_length=150, verbose_name='Имя')
    last_name = models.CharField(max_length=150, verbose_name='Фамилия')
    email = models.EmailField(max_length=150, verbose_name='Email', unique=True)
    password = models.CharField(max_length=150, verbose_name='Пароль')

    USERNAME_FIELD = 'username'
    REQUIRED_FIELDS = ['email', 'first_name', 'last_name', 'avatar']

    def __str__(self):
        return self.username

class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')
    lifetime = models.DurationField(default=datetime.timedelta(days=1))
    description = models.TextField(blank=True, verbose_name='Полное описание')
    image = models.ImageField(upload_to='question_image/', blank=True, null=True, verbose_name='Изображение')

    def is_active(self):
        return (self.pub_date + self.lifetime) > timezone.now()

    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)

    def __str__(self):
        return self.question_text


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def percentage(self):
        total_votes = sum(choice.votes for choice in self.question.choice_set.all())
        if total_votes == 0:
            return 0
        return (self.votes / total_votes) * 100

    def __str__(self):
        return self.choice_text

class Vote(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice = models.ForeignKey(Choice, on_delete=models.CASCADE)
    votes_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        unique_together = ('user', 'question')

mysite/polls/forms.py
from django import forms
from django.core.exceptions import ValidationError

from .models import User, Question


class RegistrationForm(forms.ModelForm):
    username = forms.CharField(label='Username', max_length=150)
    email = forms.EmailField(label='Email', max_length=254)
    first_name = forms.CharField(label="Имя", max_length=150)
    last_name = forms.CharField(label="Фамилия", max_length=150)
    avatar = forms.FileField(label='Загрузите свой аватар', widget=forms.FileInput, required=True)
    password = forms.CharField(label="Пароль", widget=forms.PasswordInput)
    password_confirm = forms.CharField(label="Подтвердить пароль", widget=forms.PasswordInput)

    def clean_username(self):
        username = self.cleaned_data.get('username')
        if User.objects.filter(username=username).exists():
            raise ValidationError('Такой username уже занят')
        return username

    def clean_email(self):
        email = self.cleaned_data.get('email')
        if User.objects.filter(email=email).exists():
            raise ValidationError('Такой email уже занят')
        return email

    def clean(self):
        super().clean()
        password = self.cleaned_data.get('password')
        password_confirm = self.cleaned_data.get('password_confirm')
        if password and password_confirm and password != password_confirm:
            self.add_error('password_confirm', 'Пароли не совпадают')

        return self.cleaned_data

    def save(self, commit=True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data.get("password"))
        if self.cleaned_data.get("image"):
            user.avatar = self.cleaned_data.get("image")
        if commit:
            user.save()
            return user

    class Meta:
        model = User
        fields = ('username', 'email', 'first_name', 'last_name', 'avatar')

class ProfileUpdateForm(forms.ModelForm):
    avatar = forms.FileField(label='Фото профиля', widget=forms.FileInput, required=False)
    first_name = forms.CharField(label='Имя', max_length=150, required=True)
    last_name = forms.CharField(label='Фамилия', max_length=150, required=True)
    email = forms.EmailField(label='Email', max_length=254, required=True)

    def clean_email(self):
        email = self.cleaned_data.get('email')
        if User.objects.filter(email=email).exclude(pk=self.instance.pk).exists():
            raise forms.ValidationError('Этот email уже используется.')
        return email

    class Meta:
        model = User
        fields = ['avatar', 'first_name', 'last_name', 'email']

class QuestionForm(forms.ModelForm):
    class Meta:
        model = Question
        fields = ['question_text', 'description', 'image', 'pub_date']
        widgets = {
            'pub_date': forms.DateTimeInput(attrs={'type': 'datetime-local'})
        }

mysite/polls/views.py
import datetime
from datetime import timedelta
from django.utils import timezone

from django.contrib.auth import logout
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse, HttpResponseRedirect
from django.utils.datetime_safe import datetime
from django.views.generic import DeleteView

from .forms import RegistrationForm, ProfileUpdateForm
from .models import Question, Choice, User, Vote
from django.template import loader
from django.urls import reverse, reverse_lazy
from django.views import generic, View


class IndexView(generic.ListView):
    template_name = 'polls/index.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        return Question.objects.filter(
            pub_date__lte = timezone.now(),
            pub_date__gte = timezone.now() - timedelta(days=1)
        ).order_by('-pub_date')


class DetailView(generic.DetailView):
    model = Question
    template_name = 'polls/detail.html'


class ResultsView(generic.DetailView):
    model = Question
    template_name = 'polls/results.html'


def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)

    if Vote.objects.filter(user=request.user, question=question).exists():
        messages.error(request, "Вы уже голосовали на этом вопросе. Голосовать повторно нельзя.")
        return render(request, 'polls/detail.html', {
            'question': question,
            'error_message': 'Вы уже сделали выбор...'
        })

    if request.method == 'POST':
        try:
            selected_choice = question.choice_set.get(pk=request.POST['choice'])
        except (KeyError, Choice.DoesNotExist):
            return render(request, 'polls/detail.html', {
                'question': question,
                'error_message': 'Вы не сделали выбор.'
            })
        else:
            selected_choice.votes += 1
            selected_choice.save()

            Vote.objects.create(user=request.user, question=question, choice=selected_choice)

            return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))

class Registration(generic.CreateView):
    template_name = 'polls/register.html'
    form_class = RegistrationForm
    success_url = reverse_lazy('polls:login')

def logout_view(request):
    logout(request)
    messages.success(request, 'Вы успешно вышли из аккаунта.')
    return redirect('polls:login')

class Profile(LoginRequiredMixin, generic.DetailView):
    model = User
    template_name = 'polls/profile.html'
    context_object_name = 'user_profile'

    def get_object(self, queryset=None):
        user = self.request.user
        if not user.avatar:
            messages.error(self.request, 'Пожалуйста, загрузите аватар.')
            return user

class ProfileUpdateView(LoginRequiredMixin, View):
    def get(self, request):
        form = ProfileUpdateForm(instance=request.user)
        return render(request, 'polls/profile_update.html', {'form': form})

    def post(self, request):
        form = ProfileUpdateForm(request.POST, request.FILES, instance=request.user)
        if form.is_valid():
            form.save()
            return redirect('polls:profile')
        return render(request, 'polls/profile_update.html', {'form': form})

class ProfileDeleteView(LoginRequiredMixin, DeleteView):
    model = User
    template_name = 'polls/profile_confirm_delete.html'
    success_url = reverse_lazy('polls:index')

    def get_object(self, queryset=None):
        return self.request.user

    def delete(self, request, *args, **kwargs):
        logout(request)
        messages.success(request, 'Ваш профиль был успешно удален')
        return super().delete(request, *args, **kwargs)

class AdminQuestionListView(LoginRequiredMixin, generic.ListView):
    template_name = 'polls/admin_questions.html'
    context_object_name = 'all_questions'

    def get_queryset(self):
        return Question.objects.all().order_by('-pub_date')

mysite/polls/templates/polls/admin_questions.html
{% extends 'main.html' %}

{% block content %}
<h1>Все вопросы</h1>
<ul>
    {% for question in all_questions %}
        <li>
            {{ question.question_text }} ({{ "Активен" if question.is_active else "Архив" }})
        </li>
    {% endfor %}
</ul>
<a href="{% url 'polls:index' %}">На главную</a>
{% endblock %}

mysite/polls/templates/polls/detail.html
{% extends 'main.html' %}
{% block content %}
    <h1>{{ question.question_text }}</h1>
    {% if question.image %}
        <img class="w-25" src="{{ question.image.url }}" alt="Фото вопроса">
    {% endif %}

    <p>{{ question.description }}</p>

    <form action="{% url 'polls:vote' question.id %}" method="post">
        {% csrf_token %}
        {% for choice in question.choice_set.all %}
            <div>
                <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
                <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label>
            </div>
        {% endfor %}
        <input type="submit" value="Голосовать">
        <br>
        {% if error_message %}
            <span class="text-danger">{{error_message}}</span>
        {% endif %}
    </form>
{% endblock %}

mysite/polls/templates/polls/index.html
{% extends 'main.html' %}
{% block content %}
    {% if user.is_authenticated %}
        {% if latest_question_list %}
        <ul style="list-style-type: none">
            {% for question in latest_question_list %}
            <li>
                <h2>{{ question.question_text }}</h2>
                <p>{{ question.description|truncatechars:100 }}</p>
                <a href="{% url 'polls:detail' question.id %}">Перейти к опросу</a>
            </li>
            {% endfor %}
        </ul>
        {% else %}
             <p>
                 Нет вопросов!
             </p>
        {% endif %}
    {% else %}
        <h4>Чтобы голосовать <a href="{% url 'polls:register' %}">зарегистрируйтесь</a>, или <a href="{% url 'polls:login' %}">авторизуйтесь!</a></h4>
    {% endif %}
{% endblock %}

mysite/polls/templates/polls/login.html
{% extends 'main.html' %}

<title>{% block title %}Авторизация{% endblock %}</title>

{% block content %}
<h2>Авторизация</h2>
<form class="form" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-primary">Войти</button>
</form>
{% endblock %}

mysite/polls/templates/polls/profile.html
{% extends 'main.html' %}

<title>{% block title %}Профиль{% endblock %}</title>

{% block content %}
<h1>Профиль</h1>
<br>
<div class="profile">
    <div class="avatar">
        <img src="{{ user.avatar.url }}" alt="Аватар пользователя" style="max-width: 150px; border-radius: 50%;">
    </div>
    <h2>{{ user.first_name }} {{ user.last_name }}</h2>
    <p><strong>Username:</strong> {{ user.username }}</p>
    <p><strong>Email:</strong> {{ user.email }}</p>
    <a class="btn btn-primary" href="{% url 'polls:profile_update' %}">Изменить профиль</a>
    <a class="btn btn-danger" href="{% url 'polls:profile_delete' %}">Удалить профиль</a>
</div>
{% endblock %}

mysite/polls/templates/polls/profile_confirm_delete.html
{% extends 'main.html' %}

{% block content %}
  <h1>Подтвердите удаление профиля</h1>
  <p>Вы действительно хотите удалить свой профиль? Это действие необратимо.</p>

  <form method="post">
      {% csrf_token %}
      <button type="submit" class="btn btn-danger">Удалить профиль</button>
      <a href="{% url 'polls:profile' %}" class="btn btn-secondary">Отмена</a>
  </form>
{% endblock %}

mysite/polls/templates/polls/profile_update.html
{% extends 'main.html' %}

<title>{% block title %}{% endblock %}</title>

{% block content %}
  <h1>Редактировать профиль</h1>
  <form class="form" method="post" enctype="multipart/form-data">
      {% csrf_token %}
      {{ form.as_p }}
      <button type="submit" class="btn btn-success">Сохранить изменения</button>
      <a class="btn btn-primary" href="{% url 'polls:profile' %}">Вернуться в профиль</a>
  </form>
{% endblock %}

mysite/polls/templates/polls/register.html
{% extends 'main.html' %}

<title>{% block title %}Регистрация{% endblock %}</title>

{% block content %}
<h2>Регистрация</h2>
<form class="form" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-primary">Зарегистрироваться</button>
</form>
{% endblock %}

mysite/polls/templates/polls/results.html
{% extends 'main.html' %}
{% block content %}
<h1>{{ question.question_text }}</h1>
<ul>
    {% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} голосов ({{choice.votes|floatformat:2}}%)</li>
    {% endfor %}
</ul>
{% endblock %}